//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class str_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal str_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.str_EN", typeof(str_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///List.
        /// </summary>
        internal static string cmdAreaisolamento {
            get {
                return ResourceManager.GetString("cmdAreaisolamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct.
        /// </summary>
        internal static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the P3 pre-insulated ducts .
        /// </summary>
        internal static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic
        ///Duct.
        /// </summary>
        internal static string cmdcanaledinamico {
            get {
                return ResourceManager.GetString("cmdcanaledinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a duct of type: Dynamic.
        /// </summary>
        internal static string cmdcanaledinamico_tt {
            get {
                return ResourceManager.GetString("cmdcanaledinamico_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap 
        ///Duct.
        /// </summary>
        internal static string cmdcanalescarpette {
            get {
                return ResourceManager.GetString("cmdcanalescarpette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a duct of type: Tap.
        /// </summary>
        internal static string cmdcanalescarpette_tt {
            get {
                return ResourceManager.GetString("cmdcanalescarpette_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Material.
        /// </summary>
        internal static string cmdcaricamaterial {
            get {
                return ResourceManager.GetString("cmdcaricamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload materials in the ribbonbox.
        /// </summary>
        internal static string cmdcaricamaterial_tt {
            get {
                return ResourceManager.GetString("cmdcaricamaterial_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components 
        ///Lists.
        /// </summary>
        internal static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List P3 components.
        /// </summary>
        internal static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts
        ///List.
        /// </summary>
        internal static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the P3 ducts and special pieces.
        /// </summary>
        internal static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracketing
        ///List.
        /// </summary>
        internal static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings on the P3 application.
        /// </summary>
        internal static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 Information and contacts .
        /// </summary>
        internal static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load
        ///Library.
        /// </summary>
        internal static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load P3 families and materials.
        /// </summary>
        internal static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language to italian.
        /// </summary>
        internal static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string cmdLinguaENG {
            get {
                return ResourceManager.GetString("cmdLinguaENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string cmdLinguaIT {
            get {
                return ResourceManager.GetString("cmdLinguaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change
        ///Material.
        /// </summary>
        internal static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the material of the P3 ducts.
        /// </summary>
        internal static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seismic
        ///Parameters.
        /// </summary>
        internal static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation of seismic parameters to set the ducts brackets.
        /// </summary>
        internal static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities.
        /// </summary>
        internal static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the amount of recycled material in the P3 ducts.
        /// </summary>
        internal static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracket
        ///Pre-sizing.
        /// </summary>
        internal static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic positioning and sizing of channels to structures.
        /// </summary>
        internal static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction with 2 elbows.
        /// </summary>
        internal static string Libreria_3 {
            get {
                return ResourceManager.GetString("Libreria_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbow.
        /// </summary>
        internal static string Libreria_Curva {
            get {
                return ResourceManager.GetString("Libreria_Curva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endcap.
        /// </summary>
        internal static string Libreria_Fondello {
            get {
                return ResourceManager.GetString("Libreria_Fondello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduction with elbow.
        /// </summary>
        internal static string Libreria_L {
            get {
                return ResourceManager.GetString("Libreria_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple reduction.
        /// </summary>
        internal static string Libreria_Rid1 {
            get {
                return ResourceManager.GetString("Libreria_Rid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full reduction.
        /// </summary>
        internal static string Libreria_Rid2 {
            get {
                return ResourceManager.GetString("Libreria_Rid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T connector.
        /// </summary>
        internal static string Libreria_T {
            get {
                return ResourceManager.GetString("Libreria_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double elbow.
        /// </summary>
        internal static string Libreria_Y {
            get {
                return ResourceManager.GetString("Libreria_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled Materials.
        /// </summary>
        internal static string MaterialeRiciclato {
            get {
                return ResourceManager.GetString("MaterialeRiciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling.
        /// </summary>
        internal static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities.
        /// </summary>
        internal static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seism.
        /// </summary>
        internal static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
    }
}
