//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class str_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal str_EN() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.str_EN", typeof(str_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Material
        ///List.
        /// </summary>
        internal static string cmdAreaisolamento {
            get {
                return ResourceManager.GetString("cmdAreaisolamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duct.
        /// </summary>
        internal static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Place the P3 pre-insulated ducts .
        /// </summary>
        internal static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Components 
        ///Lists.
        /// </summary>
        internal static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List P3 components.
        /// </summary>
        internal static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Price
        ///List.
        /// </summary>
        internal static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List the P3 ducts and special pieces.
        /// </summary>
        internal static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bracketing
        ///List.
        /// </summary>
        internal static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings on the P3 application.
        /// </summary>
        internal static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a P3 Information and contacts .
        /// </summary>
        internal static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load
        ///Library.
        /// </summary>
        internal static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load P3 families and materials.
        /// </summary>
        internal static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        internal static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change language to italian.
        /// </summary>
        internal static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        internal static string cmdLinguaENG {
            get {
                return ResourceManager.GetString("cmdLinguaENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        internal static string cmdLinguaIT {
            get {
                return ResourceManager.GetString("cmdLinguaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change
        ///Material.
        /// </summary>
        internal static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change the material of the P3 ducts.
        /// </summary>
        internal static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seismic
        ///Parameters.
        /// </summary>
        internal static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compilation of seismic parameters to set the ducts brackets.
        /// </summary>
        internal static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantities.
        /// </summary>
        internal static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List the amount of recycled material in the P3 ducts.
        /// </summary>
        internal static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bracket
        ///Pre-sizing.
        /// </summary>
        internal static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic positioning and sizing of channels to structures.
        /// </summary>
        internal static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        internal static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recycled Materials.
        /// </summary>
        internal static string Materiale_Riciclato {
            get {
                return ResourceManager.GetString("Materiale Riciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modeling.
        /// </summary>
        internal static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantities.
        /// </summary>
        internal static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seism.
        /// </summary>
        internal static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
    }
}
