//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class str_IT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal str_IT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.str_IT", typeof(str_IT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco
        ///Materiali.
        /// </summary>
        internal static string cmdAreaisolamento {
            get {
                return ResourceManager.GetString("cmdAreaisolamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenca i materiali utilizzati nei canali P3 e le relative superfici.
        /// </summary>
        internal static string cmdAreaisolamento_tt {
            get {
                return ResourceManager.GetString("cmdAreaisolamento_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canale.
        /// </summary>
        internal static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posiziona i canali preisolati P3.
        /// </summary>
        internal static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canale
        ///Dinamico.
        /// </summary>
        internal static string cmdcanaledinamico {
            get {
                return ResourceManager.GetString("cmdcanaledinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un condotto di tipo: Dinamico.
        /// </summary>
        internal static string cmdcanaledinamico_tt {
            get {
                return ResourceManager.GetString("cmdcanaledinamico_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canale
        ///Scarpette.
        /// </summary>
        internal static string cmdcanalescarpette {
            get {
                return ResourceManager.GetString("cmdcanalescarpette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un condotto di tipo: Scarpette.
        /// </summary>
        internal static string cmdcanalescarpette_tt {
            get {
                return ResourceManager.GetString("cmdcanalescarpette_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica Materiale.
        /// </summary>
        internal static string cmdcaricamaterial {
            get {
                return ResourceManager.GetString("cmdcaricamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica i materiali nel ribbonbox.
        /// </summary>
        internal static string cmdcaricamaterial_tt {
            get {
                return ResourceManager.GetString("cmdcaricamaterial_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco
        ///Componenti.
        /// </summary>
        internal static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenca i componenti P3.
        /// </summary>
        internal static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco
        ///Pezzi.
        /// </summary>
        internal static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenca i canali e i pezzi speciali P3.
        /// </summary>
        internal static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco
        ///Staffaggio.
        /// </summary>
        internal static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        internal static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni sull&apos;applicativo P3.
        /// </summary>
        internal static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatti.
        /// </summary>
        internal static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni e contatti P3.
        /// </summary>
        internal static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica
        ///Libreria.
        /// </summary>
        internal static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica le famiglie e i materiali P3.
        /// </summary>
        internal static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglese.
        /// </summary>
        internal static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia la lingua in inglese.
        /// </summary>
        internal static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglese.
        /// </summary>
        internal static string cmdLinguaENG {
            get {
                return ResourceManager.GetString("cmdLinguaENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string cmdLinguaIT {
            get {
                return ResourceManager.GetString("cmdLinguaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia 
        ///Materiale.
        /// </summary>
        internal static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia il materiale dei canali P3.
        /// </summary>
        internal static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametri 
        ///Sismici.
        /// </summary>
        internal static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilazione dei parametri sismici per dimensionare
        /// le staffe dei condotti.
        /// </summary>
        internal static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        internal static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenca la quantità di materiale riciclato nei canali P3.
        /// </summary>
        internal static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predimensionamento
        ///Staffaggio.
        /// </summary>
        internal static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizionamento e dimensionamento automatico dei canali alle strutture.
        /// </summary>
        internal static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione con 2 curve.
        /// </summary>
        internal static string Libreria_3 {
            get {
                return ResourceManager.GetString("Libreria_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva.
        /// </summary>
        internal static string Libreria_Curva {
            get {
                return ResourceManager.GetString("Libreria_Curva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondello.
        /// </summary>
        internal static string Libreria_Fondello {
            get {
                return ResourceManager.GetString("Libreria_Fondello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione con curva.
        /// </summary>
        internal static string Libreria_L {
            get {
                return ResourceManager.GetString("Libreria_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione semplice.
        /// </summary>
        internal static string Libreria_Rid1 {
            get {
                return ResourceManager.GetString("Libreria_Rid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione completa.
        /// </summary>
        internal static string Libreria_Rid2 {
            get {
                return ResourceManager.GetString("Libreria_Rid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connettore a T.
        /// </summary>
        internal static string Libreria_T {
            get {
                return ResourceManager.GetString("Libreria_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva doppia.
        /// </summary>
        internal static string Libreria_Y {
            get {
                return ResourceManager.GetString("Libreria_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiale Riciclato.
        /// </summary>
        internal static string MaterialeRiciclato {
            get {
                return ResourceManager.GetString("MaterialeRiciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modellazione.
        /// </summary>
        internal static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità .
        /// </summary>
        internal static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisma.
        /// </summary>
        internal static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
    }
}
