//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string bottAnnulla {
            get {
                return ResourceManager.GetString("bottAnnulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carica Libreria.
        /// </summary>
        public static string bottCaricaLibreria {
            get {
                return ResourceManager.GetString("bottCaricaLibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli Materiale.
        /// </summary>
        public static string bottScegliMateriale {
            get {
                return ResourceManager.GetString("bottScegliMateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiale.
        /// </summary>
        public static string formMateriale {
            get {
                return ResourceManager.GetString("formMateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli.
        /// </summary>
        public static string fromDettagli {
            get {
                return ResourceManager.GetString("fromDettagli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condotto.
        /// </summary>
        public static string log_Condotto {
            get {
                return ResourceManager.GetString("log_Condotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controvento per barre filettate verticali obbligatorio quando la distanza del canale dal soffitto è maggiore di.
        /// </summary>
        public static string log_Staffaggio_Controv {
            get {
                return ResourceManager.GetString("log_Staffaggio_Controv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controvento longitudinale.
        /// </summary>
        public static string log_Staffaggio_Controv_Long {
            get {
                return ResourceManager.GetString("log_Staffaggio_Controv_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controvento trasversale.
        /// </summary>
        public static string log_Staffaggio_Controv_Trasv {
            get {
                return ResourceManager.GetString("log_Staffaggio_Controv_Trasv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interasse controvento longitudinale.
        /// </summary>
        public static string log_Staffaggio_InterasseLong {
            get {
                return ResourceManager.GetString("log_Staffaggio_InterasseLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interasse controvento trasversale.
        /// </summary>
        public static string log_Staffaggio_InterasseTrasv {
            get {
                return ResourceManager.GetString("log_Staffaggio_InterasseTrasv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESSUNO.
        /// </summary>
        public static string log_Staffaggio_Nessuno {
            get {
                return ResourceManager.GetString("log_Staffaggio_Nessuno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffaggi posizionati.
        /// </summary>
        public static string log_Staffaggio_Output1 {
            get {
                return ResourceManager.GetString("log_Staffaggio_Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedere dettaglio operazioni?.
        /// </summary>
        public static string log_Staffaggio_Output2 {
            get {
                return ResourceManager.GetString("log_Staffaggio_Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo massimo.
        /// </summary>
        public static string log_Staffaggio_passo_max {
            get {
                return ResourceManager.GetString("log_Staffaggio_passo_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo minimo.
        /// </summary>
        public static string log_Staffaggio_passo_min {
            get {
                return ResourceManager.GetString("log_Staffaggio_passo_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavimenti visibili nella vista 3D al di sopra del canale:.
        /// </summary>
        public static string log_Staffaggio_PavVisibili {
            get {
                return ResourceManager.GetString("log_Staffaggio_PavVisibili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimetro condotto.
        /// </summary>
        public static string log_Staffaggio_Perim {
            get {
                return ResourceManager.GetString("log_Staffaggio_Perim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto.
        /// </summary>
        public static string log_Staffaggio_Punto {
            get {
                return ResourceManager.GetString("log_Staffaggio_Punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffa superiore.
        /// </summary>
        public static string log_Staffaggio_Sup {
            get {
                return ResourceManager.GetString("log_Staffaggio_Sup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffa superiore obbligatoria quando la distanza del canale dal soffitto è maggiore di.
        /// </summary>
        public static string log_Staffaggio_SupDist {
            get {
                return ResourceManager.GetString("log_Staffaggio_SupDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffa superiore obbligatoria quando un lato del canale è maggiore di.
        /// </summary>
        public static string log_Staffaggio_SupLato {
            get {
                return ResourceManager.GetString("log_Staffaggio_SupLato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TROPPO LONTANO.
        /// </summary>
        public static string log_Staffaggio_TroppoLontano {
            get {
                return ResourceManager.GetString("log_Staffaggio_TroppoLontano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stata trovata alcuna vista 3D.
        /// </summary>
        public static string log_Staffaggio_Vista3D_No {
            get {
                return ResourceManager.GetString("log_Staffaggio_Vista3D_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per il posizionamento degli staffaggi sarà utilizzata la seguente vista 3D di supporto,.
        /// </summary>
        public static string log_Staffaggio_Vista3D1 {
            get {
                return ResourceManager.GetString("log_Staffaggio_Vista3D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nella quale dovranno essere visibili i pavimenti a cui agganciarsi:.
        /// </summary>
        public static string log_Staffaggio_Vista3D2 {
            get {
                return ResourceManager.GetString("log_Staffaggio_Vista3D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleziona solo i condotti P3.
        /// </summary>
        public static string selezione_condotti {
            get {
                return ResourceManager.GetString("selezione_condotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona i canali a cui cambiare isolante.
        /// </summary>
        public static string selSelezionaIsolanti {
            get {
                return ResourceManager.GetString("selSelezionaIsolanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questo abaco non è presente nel progetto, caricare prima la libreria.
        /// </summary>
        public static string taskdAbachiCaricare {
            get {
                return ResourceManager.GetString("taskdAbachiCaricare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abachi non inseriti nel progetto.
        /// </summary>
        public static string taskdAbachiNoPresenti {
            get {
                return ResourceManager.GetString("taskdAbachiNoPresenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        public static string taskdErrore {
            get {
                return ResourceManager.GetString("taskdErrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile trovare e/o attivare la famiglia P3_DuctHanger.
        /// </summary>
        public static string taskdErrore_AttivazioneFam {
            get {
                return ResourceManager.GetString("taskdErrore_AttivazioneFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono stati selezionati condotti o non ce ne sono all&apos;interno del progetto.
        /// </summary>
        public static string taskdErrore_NoCanali {
            get {
                return ResourceManager.GetString("taskdErrore_NoCanali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non sono stati posizionati staffaggi : controllare la vista 3D,.
        /// </summary>
        public static string taskdErrore_NonPosizionati1 {
            get {
                return ResourceManager.GetString("taskdErrore_NonPosizionati1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la visibilità dei pavimenti e la loro distanza dai canali.
        /// </summary>
        public static string taskdErrore_NonPosizionati2 {
            get {
                return ResourceManager.GetString("taskdErrore_NonPosizionati2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provare a disinstallare e rinstallare il programma. Non è stato trovato il file .
        /// </summary>
        public static string taskdErroreFileMancante {
            get {
                return ResourceManager.GetString("taskdErroreFileMancante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolamenti mancanti.
        /// </summary>
        public static string taskdIsolMancanti {
            get {
                return ResourceManager.GetString("taskdIsolMancanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non ci sono isolamenti in questo progetto.
        /// </summary>
        public static string taskdNonCiSonoIsol {
            get {
                return ResourceManager.GetString("taskdNonCiSonoIsol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 staffaggio canali.
        /// </summary>
        public static string taskdP3StaffCan {
            get {
                return ResourceManager.GetString("taskdP3StaffCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametri sismici non inseriti nel progetto.
        /// </summary>
        public static string taskdParametriNonInseriti {
            get {
                return ResourceManager.GetString("taskdParametriNonInseriti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro associato all&apos;isolamento non esistente, inserirlo nel progetto corrente?.
        /// </summary>
        public static string taskdParametroIsolanteInserire {
            get {
                return ResourceManager.GetString("taskdParametroIsolanteInserire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro associato non esistente.
        /// </summary>
        public static string taskdParametrononEsistente {
            get {
                return ResourceManager.GetString("taskdParametrononEsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametri sismici non presenti nel progetto, caricarli?.
        /// </summary>
        public static string taskdParamInserirli {
            get {
                return ResourceManager.GetString("taskdParamInserirli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezione manuale da schermo.
        /// </summary>
        public static string taskdSelezCondottiManual {
            get {
                return ResourceManager.GetString("taskdSelezCondottiManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare la modalità di input.
        /// </summary>
        public static string taskdSelezionareMod {
            get {
                return ResourceManager.GetString("taskdSelezionareMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutti i condotti all&apos;interno del progetto Revit corrente.
        /// </summary>
        public static string taskdSelezTuttiCondotti {
            get {
                return ResourceManager.GetString("taskdSelezTuttiCondotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì.
        /// </summary>
        public static string taskdSì {
            get {
                return ResourceManager.GetString("taskdSì", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le staffe non sono caricate nel progetto, caricare prima la libreria.
        /// </summary>
        public static string taskdStaffeCaricarle {
            get {
                return ResourceManager.GetString("taskdStaffeCaricarle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffe non inseriti nel progetto.
        /// </summary>
        public static string taskdStaffeNonInserite {
            get {
                return ResourceManager.GetString("taskdStaffeNonInserite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi di condotti non inseriti nel progetto, caricare prima la libreria.
        /// </summary>
        public static string taskdTipiCanaleCaricare {
            get {
                return ResourceManager.GetString("taskdTipiCanaleCaricare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi di canale non inseriti nel progetto.
        /// </summary>
        public static string taskdTipiNonPresenti {
            get {
                return ResourceManager.GetString("taskdTipiNonPresenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporanee.
        /// </summary>
        public static string Temporary {
            get {
                return ResourceManager.GetString("Temporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test2.
        /// </summary>
        public static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test3.
        /// </summary>
        public static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posiziona staffaggio.
        /// </summary>
        public static string transaction_PosizionaStaffaggio {
            get {
                return ResourceManager.GetString("transaction_PosizionaStaffaggio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerazione.
        /// </summary>
        public static string wpfAccel {
            get {
                return ResourceManager.GetString("wpfAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserisci il valore di accelerazione sismica  αg/g.
        /// </summary>
        public static string wpfAccInserireVal {
            get {
                return ResourceManager.GetString("wpfAccInserireVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        public static string wpfImpAttivo {
            get {
                return ResourceManager.GetString("wpfImpAttivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTEZZA MASSIMA DI STAFFAGGIO.
        /// </summary>
        public static string wpfimpoAltezzaMax {
            get {
                return ResourceManager.GetString("wpfimpoAltezzaMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attivo.
        /// </summary>
        public static string wpfImpoAttivo {
            get {
                return ResourceManager.GetString("wpfImpoAttivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;updater è una funzione appositamente sviluppata su questo applicativo che ti permette di creare all&apos;interno del progetto corrnete, canali P3 già dotati di isolante e caratteristiche di fabbrica.
        ///
        ///Questa funzione legge in backround le operazione svolte sui condotti e interviene quando ne viene creato uno nuovo, se ritieni di non aver bisogno di questa funzione o riscontri eccessivi rallentamenti nel tuo progetto puoi interrompere temporaneamente questa funzionalità.
        /// </summary>
        public static string wpfImpoContent {
            get {
                return ResourceManager.GetString("wpfImpoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposta l&apos;altezza massima per la quale è necessario lo staffaggio dei condotti.
        /// </summary>
        public static string wpfimpoImpoAltezza {
            get {
                return ResourceManager.GetString("wpfimpoImpoAltezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposta.
        /// </summary>
        public static string wpfimpoImposta {
            get {
                return ResourceManager.GetString("wpfimpoImposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPOSTAZIONI PLUGIN.
        /// </summary>
        public static string wpfimpoImpostazioni {
            get {
                return ResourceManager.GetString("wpfimpoImpostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondello.
        /// </summary>
        public static string wpfLChiusura {
            get {
                return ResourceManager.GetString("wpfLChiusura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviazione con due curve.
        /// </summary>
        public static string wpfLDerivazioneaIncrocio {
            get {
                return ResourceManager.GetString("wpfLDerivazioneaIncrocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva doppia.
        /// </summary>
        public static string wpfLDerivazioneaY {
            get {
                return ResourceManager.GetString("wpfLDerivazioneaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione con curva.
        /// </summary>
        public static string wpfLDerivazioneLaterale {
            get {
                return ResourceManager.GetString("wpfLDerivazioneLaterale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connettore a T.
        /// </summary>
        public static string wpfLDerivazioneT {
            get {
                return ResourceManager.GetString("wpfLDerivazioneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connettore a T a settori.
        /// </summary>
        public static string wpfLDerivazioneTsector {
            get {
                return ResourceManager.GetString("wpfLDerivazioneTsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva.
        /// </summary>
        public static string wpfLGomito {
            get {
                return ResourceManager.GetString("wpfLGomito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gomito.
        /// </summary>
        public static string wpfLGomito90 {
            get {
                return ResourceManager.GetString("wpfLGomito90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curva a settori.
        /// </summary>
        public static string wpfLGomitoSector {
            get {
                return ResourceManager.GetString("wpfLGomitoSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incrocio a 4 vie.
        /// </summary>
        public static string wpfLIncrocioSector {
            get {
                return ResourceManager.GetString("wpfLIncrocioSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plenum.
        /// </summary>
        public static string wpfLPlenum {
            get {
                return ResourceManager.GetString("wpfLPlenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione semplice.
        /// </summary>
        public static string wpfLRiduzioneCostante {
            get {
                return ResourceManager.GetString("wpfLRiduzioneCostante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riduzione completa.
        /// </summary>
        public static string wpfLRiduzioneVariabile {
            get {
                return ResourceManager.GetString("wpfLRiduzioneVariabile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarpetta.
        /// </summary>
        public static string wpfLScarpetta {
            get {
                return ResourceManager.GetString("wpfLScarpetta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni con presenza solo occasionale di persone 
        ///| Edifici agricoli.
        /// </summary>
        public static string wpfPCu1 {
            get {
                return ResourceManager.GetString("wpfPCu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni cui uso preveda normali affollamenti senza contenuti pericolosi per l&apos;ambiente e senza funzioni pubbliche e  sociali essenziali. Industie con attività non pericolose per l&apos;ambiente 
        ///| Uffici.
        /// </summary>
        public static string wpfPCu2 {
            get {
                return ResourceManager.GetString("wpfPCu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni il cui uso preveda affollamenti signifficativi. Industrie con attività pericolose per l&apos;ambiente 
        ///| Centri commerciali.
        /// </summary>
        public static string wpfPCu3 {
            get {
                return ResourceManager.GetString("wpfPCu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costruzioni con funzioni pubbliche o strategiche importanti, anche con riferimento alla gestione della protezione civile in caso di calimità. Industrie con attività particolarmente pericolose 
        ///| Ospedali.
        /// </summary>
        public static string wpfPCu4 {
            get {
                return ResourceManager.GetString("wpfPCu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIZIONE ACCELERAZIONE SISMICA.
        /// </summary>
        public static string wpfPDefAcc {
            get {
                return ResourceManager.GetString("wpfPDefAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definizione accelerazione sismica αg/g.
        /// </summary>
        public static string wpfPDefAccag {
            get {
                return ResourceManager.GetString("wpfPDefAccag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFINIZIONE CLASSE D&apos;USO.
        /// </summary>
        public static string wpfPDefCu {
            get {
                return ResourceManager.GetString("wpfPDefCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caricare la libreria prima di scegliere il materiale.
        /// </summary>
        public static string wpfPrbpCaricareMat {
            get {
                return ResourceManager.GetString("wpfPrbpCaricareMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisimicità alta 
        ///(0.25 &lt; α  ≤ 0.35).
        /// </summary>
        public static string wpfPSism1 {
            get {
                return ResourceManager.GetString("wpfPSism1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisimicità medio-alta 
        ///(0.15 &lt; α  ≤ 0.25).
        /// </summary>
        public static string wpfPSism2 {
            get {
                return ResourceManager.GetString("wpfPSism2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisimicità  medio-bassa 
        ///(0.05 &lt; α  ≤ 0.15).
        /// </summary>
        public static string wpfPSism3 {
            get {
                return ResourceManager.GetString("wpfPSism3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisimicità bassa 
        ///( α  ≤ 0.05).
        /// </summary>
        public static string wpfPSism4 {
            get {
                return ResourceManager.GetString("wpfPSism4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONA 1.
        /// </summary>
        public static string wpfPz1 {
            get {
                return ResourceManager.GetString("wpfPz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONA 2.
        /// </summary>
        public static string wpfPz2 {
            get {
                return ResourceManager.GetString("wpfPz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONA 3.
        /// </summary>
        public static string wpfPz3 {
            get {
                return ResourceManager.GetString("wpfPz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONA 4.
        /// </summary>
        public static string wpfPz4 {
            get {
                return ResourceManager.GetString("wpfPz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZONA SISMICA.
        /// </summary>
        public static string wpfPZonaSismica {
            get {
                return ResourceManager.GetString("wpfPZonaSismica", resourceCulture);
            }
        }
    }
}
