//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica Libreria.
        /// </summary>
        public static string bottCaricaLibreria {
            get {
                return ResourceManager.GetString("bottCaricaLibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegli Materiale.
        /// </summary>
        public static string bottScegliMateriale {
            get {
                return ResourceManager.GetString("bottScegliMateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco
        ///Materiali.
        /// </summary>
        public static string cmdAreaisolamento {
            get {
                return ResourceManager.GetString("cmdAreaisolamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenca i materiali utilizzati nei canali P3 e le relative superfici.
        /// </summary>
        public static string cmdAreaisolamento_tt {
            get {
                return ResourceManager.GetString("cmdAreaisolamento_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canale.
        /// </summary>
        public static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posiziona i canali preisolati P3.
        /// </summary>
        public static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canale
        ///Dinamico.
        /// </summary>
        public static string cmdcanaledinamico {
            get {
                return ResourceManager.GetString("cmdcanaledinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea un condotto di tipo: Dinamico.
        /// </summary>
        public static string cmdcanaledinamico_tt {
            get {
                return ResourceManager.GetString("cmdcanaledinamico_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canale
        ///Scarpette.
        /// </summary>
        public static string cmdcanalescarpette {
            get {
                return ResourceManager.GetString("cmdcanalescarpette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea un condotto di tipo: Scarpette.
        /// </summary>
        public static string cmdcanalescarpette_tt {
            get {
                return ResourceManager.GetString("cmdcanalescarpette_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica Materiale.
        /// </summary>
        public static string cmdcaricamaterial {
            get {
                return ResourceManager.GetString("cmdcaricamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica i materiali nel ribbonbox.
        /// </summary>
        public static string cmdcaricamaterial_tt {
            get {
                return ResourceManager.GetString("cmdcaricamaterial_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco
        ///Componenti.
        /// </summary>
        public static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenca i componenti P3.
        /// </summary>
        public static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco
        ///Pezzi.
        /// </summary>
        public static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenca i canali e i pezzi speciali P3.
        /// </summary>
        public static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco
        ///Punti.
        /// </summary>
        public static string cmdelencopunti {
            get {
                return ResourceManager.GetString("cmdelencopunti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenca gli staffaggi utilizzati e la relativa componentistica.
        /// </summary>
        public static string cmdelencopunti_tt {
            get {
                return ResourceManager.GetString("cmdelencopunti_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco
        ///Staffaggio.
        /// </summary>
        public static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        public static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni sull&apos;applicativo P3.
        /// </summary>
        public static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contatti.
        /// </summary>
        public static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni e contatti P3.
        /// </summary>
        public static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica
        ///Libreria.
        /// </summary>
        public static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica le famiglie e i materiali P3.
        /// </summary>
        public static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inglese.
        /// </summary>
        public static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cambia la lingua in inglese.
        /// </summary>
        public static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inglese.
        /// </summary>
        public static string cmdLinguaENG {
            get {
                return ResourceManager.GetString("cmdLinguaENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italiano.
        /// </summary>
        public static string cmdLinguaIT {
            get {
                return ResourceManager.GetString("cmdLinguaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cambia 
        ///Materiale.
        /// </summary>
        public static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cambia il materiale dei canali P3.
        /// </summary>
        public static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametri 
        ///Sismici.
        /// </summary>
        public static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compilazione dei parametri sismici per dimensionare
        /// le staffe dei condotti.
        /// </summary>
        public static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità.
        /// </summary>
        public static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenca la quantità di materiale riciclato nei canali P3.
        /// </summary>
        public static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Predimensionamento
        ///Staffaggio.
        /// </summary>
        public static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posizionamento e dimensionamento automatico dei canali alle strutture.
        /// </summary>
        public static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        public static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Materiale Riciclato.
        /// </summary>
        public static string Materiale_Riciclato {
            get {
                return ResourceManager.GetString("Materiale Riciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modellazione.
        /// </summary>
        public static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantità .
        /// </summary>
        public static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sisma.
        /// </summary>
        public static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiusura.
        /// </summary>
        public static string wpfChiusura {
            get {
                return ResourceManager.GetString("wpfChiusura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a Incrocio.
        /// </summary>
        public static string wpfDerivazioneaIncrocio {
            get {
                return ResourceManager.GetString("wpfDerivazioneaIncrocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a Y.
        /// </summary>
        public static string wpfDerivazioneaY {
            get {
                return ResourceManager.GetString("wpfDerivazioneaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione Laterale.
        /// </summary>
        public static string wpfDerivazioneLaterale {
            get {
                return ResourceManager.GetString("wpfDerivazioneLaterale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a T.
        /// </summary>
        public static string wpfDeviazioneT {
            get {
                return ResourceManager.GetString("wpfDeviazioneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gomito.
        /// </summary>
        public static string wpfGomito {
            get {
                return ResourceManager.GetString("wpfGomito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riduzione costante.
        /// </summary>
        public static string wpfRiduzioneCostante {
            get {
                return ResourceManager.GetString("wpfRiduzioneCostante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riduzione Variabile.
        /// </summary>
        public static string wpfRiduzioneVariabile {
            get {
                return ResourceManager.GetString("wpfRiduzioneVariabile", resourceCulture);
            }
        }
    }
}
