//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string bottAnnulla {
            get {
                return ResourceManager.GetString("bottAnnulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica Libreria.
        /// </summary>
        public static string bottCaricaLibreria {
            get {
                return ResourceManager.GetString("bottCaricaLibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegli Materiale.
        /// </summary>
        public static string bottScegliMateriale {
            get {
                return ResourceManager.GetString("bottScegliMateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore.
        /// </summary>
        public static string taskdErrore {
            get {
                return ResourceManager.GetString("taskdErrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Isolamenti mancanti.
        /// </summary>
        public static string taskdIsolMancanti {
            get {
                return ResourceManager.GetString("taskdIsolMancanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non ci sono isolamenti in questo progetto.
        /// </summary>
        public static string taskdNonCiSonoIsol {
            get {
                return ResourceManager.GetString("taskdNonCiSonoIsol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a P3 staffaggio canali.
        /// </summary>
        public static string taskdP3StaffCan {
            get {
                return ResourceManager.GetString("taskdP3StaffCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametri sismici non inseriti nel progetto.
        /// </summary>
        public static string taskdParametriNonInseriti {
            get {
                return ResourceManager.GetString("taskdParametriNonInseriti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametro associato all&apos;isolamento non esistente, inserirlo nel progetto corrente?.
        /// </summary>
        public static string taskdParametroIsolanteInserire {
            get {
                return ResourceManager.GetString("taskdParametroIsolanteInserire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametro associato non esistente.
        /// </summary>
        public static string taskdParametrononEsistente {
            get {
                return ResourceManager.GetString("taskdParametrononEsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parametri sismici non presenti nel progetto, caricarli?.
        /// </summary>
        public static string taskdParamInserirli {
            get {
                return ResourceManager.GetString("taskdParamInserirli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezione manuale da schermo.
        /// </summary>
        public static string taskdSelezCondottiManual {
            get {
                return ResourceManager.GetString("taskdSelezCondottiManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare la modalità di input.
        /// </summary>
        public static string taskdSelezionareMod {
            get {
                return ResourceManager.GetString("taskdSelezionareMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona tutti i condotti all&apos;interno del progetto Revit corrente.
        /// </summary>
        public static string taskdSelezTuttiCondotti {
            get {
                return ResourceManager.GetString("taskdSelezTuttiCondotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sì.
        /// </summary>
        public static string taskdSì {
            get {
                return ResourceManager.GetString("taskdSì", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Le staffe non sono caricate nel progetto, caricare prima la libreria.
        /// </summary>
        public static string taskdStaffeCaricarle {
            get {
                return ResourceManager.GetString("taskdStaffeCaricarle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Staffe non inseriti nel progetto.
        /// </summary>
        public static string taskdStaffeNonInserite {
            get {
                return ResourceManager.GetString("taskdStaffeNonInserite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiusura.
        /// </summary>
        public static string wpfLChiusura {
            get {
                return ResourceManager.GetString("wpfLChiusura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a Incrocio.
        /// </summary>
        public static string wpfLDerivazioneaIncrocio {
            get {
                return ResourceManager.GetString("wpfLDerivazioneaIncrocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a Y.
        /// </summary>
        public static string wpfLDerivazioneaY {
            get {
                return ResourceManager.GetString("wpfLDerivazioneaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione Laterale.
        /// </summary>
        public static string wpfLDerivazioneLaterale {
            get {
                return ResourceManager.GetString("wpfLDerivazioneLaterale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Derivazione a T.
        /// </summary>
        public static string wpfLDerivazioneT {
            get {
                return ResourceManager.GetString("wpfLDerivazioneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gomito.
        /// </summary>
        public static string wpfLGomito {
            get {
                return ResourceManager.GetString("wpfLGomito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riduzione costante.
        /// </summary>
        public static string wpfLRiduzioneCostante {
            get {
                return ResourceManager.GetString("wpfLRiduzioneCostante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riduzione Variabile.
        /// </summary>
        public static string wpfLRiduzioneVariabile {
            get {
                return ResourceManager.GetString("wpfLRiduzioneVariabile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costruzioni con presenza solo occasionale di persone | Edifici agricoli.
        /// </summary>
        public static string wpfPCu1 {
            get {
                return ResourceManager.GetString("wpfPCu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costruzioni cui uso preveda normali 
        ///affollamenti senza contenuti pericolosi per
        /// l&apos;ambiente e senza funzioni pubbliche e 
        ///sociali essenziali. Industie con attività non
        /// pericolose per l&apos;ambiente | Uffici.
        /// </summary>
        public static string wpfPCu2 {
            get {
                return ResourceManager.GetString("wpfPCu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costruzioni il cui uso preveda affollamenti 
        ///signifficativi. Industrie con attività pericolose 
        ///per l&apos;ambiente | Centri commerciali.
        /// </summary>
        public static string wpfPCu3 {
            get {
                return ResourceManager.GetString("wpfPCu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costruzioni con funzioni pubbliche 
        ///o strategiche importanti, anche con 
        ///riferimento alla gestione della protezione
        /// civile in caso di calimità. Industrie con 
        ///attività particolarmente pericolose | Ospedali.
        /// </summary>
        public static string wpfPCu4 {
            get {
                return ResourceManager.GetString("wpfPCu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DEFINIZIONE ACCELLERAZIONE SISMICA.
        /// </summary>
        public static string wpfPDefAcc {
            get {
                return ResourceManager.GetString("wpfPDefAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DEFINIZIONE CLASSE D&apos;USO.
        /// </summary>
        public static string wpfPDefCu {
            get {
                return ResourceManager.GetString("wpfPDefCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricare la libreria prima di scegliere il materiale.
        /// </summary>
        public static string wpfPrbpCaricareMat {
            get {
                return ResourceManager.GetString("wpfPrbpCaricareMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sisimicità alta (0.25 &lt; α  ≤ 0.35).
        /// </summary>
        public static string wpfPSism1 {
            get {
                return ResourceManager.GetString("wpfPSism1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sisimicità medio-alta (0.15 &lt; α  ≤ 0.25).
        /// </summary>
        public static string wpfPSism2 {
            get {
                return ResourceManager.GetString("wpfPSism2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sisimicità  medio-bassa (0.05 &lt; α  ≤ 0.15).
        /// </summary>
        public static string wpfPSism3 {
            get {
                return ResourceManager.GetString("wpfPSism3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sisimicità bassa ( α  ≤ 0.05).
        /// </summary>
        public static string wpfPSism4 {
            get {
                return ResourceManager.GetString("wpfPSism4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZONA 1.
        /// </summary>
        public static string wpfPz1 {
            get {
                return ResourceManager.GetString("wpfPz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZONA 2.
        /// </summary>
        public static string wpfPz2 {
            get {
                return ResourceManager.GetString("wpfPz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZONA 3.
        /// </summary>
        public static string wpfPz3 {
            get {
                return ResourceManager.GetString("wpfPz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZONA 4.
        /// </summary>
        public static string wpfPz4 {
            get {
                return ResourceManager.GetString("wpfPz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ZONA SISMICA.
        /// </summary>
        public static string wpfPZonaSismica {
            get {
                return ResourceManager.GetString("wpfPZonaSismica", resourceCulture);
            }
        }
    }
}
