//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rp_ENG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rp_ENG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.Lang.rp_ENG", typeof(rp_ENG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct.
        /// </summary>
        public static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the P3 pre-insulated ducts .
        /// </summary>
        public static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duct.
        /// </summary>
        public static string cmdcanaledinamico {
            get {
                return ResourceManager.GetString("cmdcanaledinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a duct of type: Dynamic.
        /// </summary>
        public static string cmdcanaledinamico_tt {
            get {
                return ResourceManager.GetString("cmdcanaledinamico_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular 
        ///Takeoff.
        /// </summary>
        public static string cmdcanalescarpette {
            get {
                return ResourceManager.GetString("cmdcanalescarpette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a duct of type: Tap.
        /// </summary>
        public static string cmdcanalescarpette_tt {
            get {
                return ResourceManager.GetString("cmdcanalescarpette_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Library.
        /// </summary>
        public static string cmdCaricaLibreria {
            get {
                return ResourceManager.GetString("cmdCaricaLibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load families and materials P3.
        /// </summary>
        public static string cmdCaricaLibreria_tt {
            get {
                return ResourceManager.GetString("cmdCaricaLibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Material.
        /// </summary>
        public static string cmdcaricamaterial {
            get {
                return ResourceManager.GetString("cmdcaricamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload materials in the ribbonbox.
        /// </summary>
        public static string cmdcaricamaterial_tt {
            get {
                return ResourceManager.GetString("cmdcaricamaterial_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components 
        ///Lists.
        /// </summary>
        public static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List brakets .
        /// </summary>
        public static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts
        ///List.
        /// </summary>
        public static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the pieces and materials.
        /// </summary>
        public static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points
        ///Lists.
        /// </summary>
        public static string cmdelencopunti {
            get {
                return ResourceManager.GetString("cmdelencopunti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists P3 components.
        /// </summary>
        public static string cmdelencopunti_tt {
            get {
                return ResourceManager.GetString("cmdelencopunti_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracketing
        ///List.
        /// </summary>
        public static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the fixtures used and the related components.
        /// </summary>
        public static string cmdelencostaffaggi_tt {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings on the P3 application.
        /// </summary>
        public static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3 Information and contacts .
        /// </summary>
        public static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load
        ///Library.
        /// </summary>
        public static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load P3 families and materials.
        /// </summary>
        public static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language to italian.
        /// </summary>
        public static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///List.
        /// </summary>
        public static string cmdlistamateriali {
            get {
                return ResourceManager.GetString("cmdlistamateriali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists the materials used in the P3 channels and their surfaces.
        /// </summary>
        public static string cmdlistamateriali_tt {
            get {
                return ResourceManager.GetString("cmdlistamateriali_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change
        ///Material.
        /// </summary>
        public static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the material of the P3 ducts.
        /// </summary>
        public static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seismic
        ///Parameters.
        /// </summary>
        public static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation of seismic parameters to set the ducts brackets.
        /// </summary>
        public static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities.
        /// </summary>
        public static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the amount of recycled material in the P3 ducts.
        /// </summary>
        public static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracket
        ///Pre-sizing.
        /// </summary>
        public static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic positioning and sizing of channels to structures.
        /// </summary>
        public static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled Materials.
        /// </summary>
        public static string Materiale_Riciclato {
            get {
                return ResourceManager.GetString("Materiale Riciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeling.
        /// </summary>
        public static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities.
        /// </summary>
        public static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seism.
        /// </summary>
        public static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
    }
}
