//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Ribbon.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rp_ENG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rp_ENG() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P3Ribbon.Resources.Lang.rp_ENG", typeof(rp_ENG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duct.
        /// </summary>
        public static string cmdcanale {
            get {
                return ResourceManager.GetString("cmdcanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Place the P3 pre-insulated ducts .
        /// </summary>
        public static string cmdcanale_tt {
            get {
                return ResourceManager.GetString("cmdcanale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duct.
        /// </summary>
        public static string cmdcanaledinamico {
            get {
                return ResourceManager.GetString("cmdcanaledinamico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a duct of type: Dynamic.
        /// </summary>
        public static string cmdcanaledinamico_tt {
            get {
                return ResourceManager.GetString("cmdcanaledinamico_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rectangular 
        ///Tackeoff.
        /// </summary>
        public static string cmdcanalescarpette {
            get {
                return ResourceManager.GetString("cmdcanalescarpette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create a duct of type: Tap.
        /// </summary>
        public static string cmdcanalescarpette_tt {
            get {
                return ResourceManager.GetString("cmdcanalescarpette_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Library.
        /// </summary>
        public static string cmdCaricaLibreria {
            get {
                return ResourceManager.GetString("cmdCaricaLibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load families and materials P3.
        /// </summary>
        public static string cmdCaricaLibreria_tt {
            get {
                return ResourceManager.GetString("cmdCaricaLibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload Material.
        /// </summary>
        public static string cmdcaricamaterial {
            get {
                return ResourceManager.GetString("cmdcaricamaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload materials in the ribbonbox.
        /// </summary>
        public static string cmdcaricamaterial_tt {
            get {
                return ResourceManager.GetString("cmdcaricamaterial_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Components 
        ///Lists.
        /// </summary>
        public static string cmdelencocomp {
            get {
                return ResourceManager.GetString("cmdelencocomp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List brakets .
        /// </summary>
        public static string cmdelencocomp_tt {
            get {
                return ResourceManager.GetString("cmdelencocomp_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parts
        ///List.
        /// </summary>
        public static string cmdelencopezzi {
            get {
                return ResourceManager.GetString("cmdelencopezzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List the P3 ducts and special pieces.
        /// </summary>
        public static string cmdelencopezzi_tt {
            get {
                return ResourceManager.GetString("cmdelencopezzi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Points
        ///Lists.
        /// </summary>
        public static string cmdelencopunti {
            get {
                return ResourceManager.GetString("cmdelencopunti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lists P3 components.
        /// </summary>
        public static string cmdelencopunti_tt {
            get {
                return ResourceManager.GetString("cmdelencopunti_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bracketing
        ///List.
        /// </summary>
        public static string cmdelencostaffaggi {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lists the fixtures used and the related components.
        /// </summary>
        public static string cmdelencostaffaggi_tt {
            get {
                return ResourceManager.GetString("cmdelencostaffaggi_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string cmdimpo {
            get {
                return ResourceManager.GetString("cmdimpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings on the P3 application.
        /// </summary>
        public static string cmdimpo_tt {
            get {
                return ResourceManager.GetString("cmdimpo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        public static string cmdinfo {
            get {
                return ResourceManager.GetString("cmdinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a P3 Information and contacts .
        /// </summary>
        public static string cmdinfo_tt {
            get {
                return ResourceManager.GetString("cmdinfo_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load
        ///Library.
        /// </summary>
        public static string cmdlibreria {
            get {
                return ResourceManager.GetString("cmdlibreria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load P3 families and materials.
        /// </summary>
        public static string cmdlibreria_tt {
            get {
                return ResourceManager.GetString("cmdlibreria_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        public static string cmdlingua {
            get {
                return ResourceManager.GetString("cmdlingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change language to italian.
        /// </summary>
        public static string cmdlingua_tt {
            get {
                return ResourceManager.GetString("cmdlingua_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        public static string cmdLinguaENG {
            get {
                return ResourceManager.GetString("cmdLinguaENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        public static string cmdLinguaIT {
            get {
                return ResourceManager.GetString("cmdLinguaIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Material
        ///List.
        /// </summary>
        public static string cmdlistamateriali {
            get {
                return ResourceManager.GetString("cmdlistamateriali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lists the materials used in the P3 channels and their surfaces.
        /// </summary>
        public static string cmdlistamateriali_tt {
            get {
                return ResourceManager.GetString("cmdlistamateriali_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change
        ///Material.
        /// </summary>
        public static string cmdmateriale {
            get {
                return ResourceManager.GetString("cmdmateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change the material of the P3 ducts.
        /// </summary>
        public static string cmdmateriale_tt {
            get {
                return ResourceManager.GetString("cmdmateriale_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seismic
        ///Parameters.
        /// </summary>
        public static string cmdParsism {
            get {
                return ResourceManager.GetString("cmdParsism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compilation of seismic parameters to set the ducts brackets.
        /// </summary>
        public static string cmdParsism_tt {
            get {
                return ResourceManager.GetString("cmdParsism_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantities.
        /// </summary>
        public static string cmdquantità {
            get {
                return ResourceManager.GetString("cmdquantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a List the amount of recycled material in the P3 ducts.
        /// </summary>
        public static string cmdquantità_tt {
            get {
                return ResourceManager.GetString("cmdquantità_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bracket
        ///Pre-sizing.
        /// </summary>
        public static string cmdstaff {
            get {
                return ResourceManager.GetString("cmdstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic positioning and sizing of channels to structures.
        /// </summary>
        public static string cmdstaff_tt {
            get {
                return ResourceManager.GetString("cmdstaff_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info.
        /// </summary>
        public static string Informazioni {
            get {
                return ResourceManager.GetString("Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recycled Materials.
        /// </summary>
        public static string Materiale_Riciclato {
            get {
                return ResourceManager.GetString("Materiale Riciclato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modeling.
        /// </summary>
        public static string Modellazione {
            get {
                return ResourceManager.GetString("Modellazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantities.
        /// </summary>
        public static string Quantità {
            get {
                return ResourceManager.GetString("Quantità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seism.
        /// </summary>
        public static string Sisma {
            get {
                return ResourceManager.GetString("Sisma", resourceCulture);
            }
        }
    }
}
